import java.util.*;
import java.io.*;

public class Course implements Comparable<Course>,Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L; //generated by elcipse
	private String courseName, courseID, instructor, sectionNum, location;
	private ArrayList<Student> nameList;
	private int maxStu, currentStu;
	
	public Course() {//constructor
		
	}
	
	public Course(String name, String id, String max, String current, ArrayList<Student> nameList, String instructor, String section, String location) {
		courseName = name;
		courseID = id;
		maxStu = Integer.parseInt(max);
		currentStu = Integer.parseInt(current);//change string into int
		this.nameList = nameList;
		this.instructor = instructor;
		sectionNum = section;
		this.location = location;
	}

	//getters and setters generated by eclipse source tab
	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getCourseID() {
		return courseID;
	}

	public void setCourseID(String courseID) {
		this.courseID = courseID;
	}

	public ArrayList<Student> getNameList() {
		return nameList;
	}

	public void setNameList(ArrayList<Student> nameList) {
		this.nameList = nameList;
	}

	public String getInstructor() {
		return instructor;
	}

	public void setInstructor(String instructor) {
		this.instructor = instructor;
	}

	public String getSectionNum() {
		return sectionNum;
	}

	public void setSectionNum(String sectionNum) {
		this.sectionNum = sectionNum;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public int getMaxStu() {
		return maxStu;
	}

	public void setMaxStu(int maxStu) {
		this.maxStu = maxStu;
	}

	public int getCurrentStu() {
		return currentStu;
	}

	public void setCurrentStu(int currentStu) {
		this.currentStu = currentStu;
	}

	@Override
	public String toString() { 
		return courseName + " "+  courseID + " [] "+ instructor + " "+sectionNum + " "+location + " "+maxStu + " "+currentStu;
	}
	
	public int compareTo(Course c) { //compare courses based on their currentStu number
	       
	    	if(this.currentStu == c.currentStu)
	            return 0;
	        else if (this.currentStu > c.currentStu) 
	        	return 1;
	        else 
	        	return -1;
	           
	    }
	


}
