import java.util.*;

public class User implements java.io.Serializable{
	
	protected String username;
	protected String password;
	protected String firstName;
	protected String lastName; //some data fields; protected because children class needs to access these
	
	public static ArrayList<Course> allcourses; 

	
	public User() {//default constructor
		
	}
	
	public User(String username, String password, String firstName, String lastName) {//constructor
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
	}
	
	//getters and setters generated by Eclipse source tab
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	

}
